// Code generated by scripts/update-tool-checksums.sh; DO NOT EDIT.
// Run `scripts/update-tool-checksums.sh` after bumping a pinned version.

package tools

// pinnedVersion is the version devrig fetches and validates per tool.
var pinnedVersion = map[Tool]string{
	Kubectl: "1.36.2",
	Helm:    "3.21.1",
	K3d:     "5.9.0",
}

// checksums maps "<tool>/<version>/<goos>/<goarch>" to the expected
// SHA-256 of the downloaded artifact (the raw binary for kubectl/k3d, the
// .tar.gz for helm).
var checksums = map[string]string{
	"kubectl/1.36.2/linux/amd64":   "1e9045ec32bea85da43de85f0065358529ea7c7a152eca78154fba5b58c27d82",
	"helm/3.21.1/linux/amd64":      "a349c62d6ab2d5d11f044fc0d3afa6deed7d27cc7d5c351f536b169d9fc2cc1a",
	"k3d/5.9.0/linux/amd64":        "06d8f25bc3a971c4eb29e0ff08429b180402db0f4dec838c9eac427e296800a0",
	"kubectl/1.36.2/linux/arm64":   "c957eb8c4bea27a3bb35b269edd9082e27f027f7b76b20b5bf4afebc726c6d3e",
	"helm/3.21.1/linux/arm64":      "9b3deeecb56c4795aa806858fa4d6388c049e3edfcd771723bd12c1cbef66893",
	"k3d/5.9.0/linux/arm64":        "03cde5cf23e6e8e67de5a039ecf26e5b85aca82fba3e5d13dadf904cd218a250",
	"kubectl/1.36.2/darwin/amd64":  "ce6c5e55cd17559e87e4fb5e73ebbbc2511bcf2b695d7a40c1b1461a9817d4b3",
	"helm/3.21.1/darwin/amd64":     "dd353172bc8cef8c1845501043b82224520a79ff8b2cd4388ec5bfa060ce96b9",
	"k3d/5.9.0/darwin/amd64":       "b4aabc37534f95b9c764e7823f2df923f50d57600837aa60a06266cce47db732",
	"kubectl/1.36.2/darwin/arm64":  "4408c85c83fd3a31adaa555bdf3c7a6c81f74b19449a9060ba31ab91926f023d",
	"helm/3.21.1/darwin/arm64":     "779ac09ad0cf333b12402555a32bd26174462384aba2f5a3845876f45d34146a",
	"k3d/5.9.0/darwin/arm64":       "fe106541d5d0a3f18debcd4d432a16f8c0ce3e6ddc06f8fbb6f696a122313e00",
	"kubectl/1.36.2/windows/amd64": "df04d82234b28ffbdcd36e79d596b85da6e9c736e1a7a55ff6910c648ff47af2",
	"helm/3.21.1/windows/amd64":    "c85b10a79daf07622969b0afa9c2a4d6766ca095b69a4415bbc07365b7a304c4",
	"k3d/5.9.0/windows/amd64":      "49d0b9c796f5b8ba6f58a1dd5469e8b7b34bf9b6ce9078633eedb2789680a034",
}
