#!/usr/bin/env bash
# Regenerates internal/tools/checksums_gen.go with SHA-256 checksums for the
# pinned k3d/kubectl/helm versions across every supported platform.
#
# Pinned versions live here (single source of truth). Bump them, re-run this
# script, and commit the result. CI re-verifies every checksum by downloading.
set -euo pipefail

KUBECTL_VERSION="1.36.2"
HELM_VERSION="3.21.1"
K3D_VERSION="5.9.0"

# goos/goarch pairs devrig supports for managed tools. k3d ships no windows/arm64.
PLATFORMS=(
  "linux/amd64"
  "linux/arm64"
  "darwin/amd64"
  "darwin/arm64"
  "windows/amd64"
)

out="internal/tools/checksums_gen.go"
tmp="$(mktemp)"

emit() { printf '%s\n' "$1" >>"$tmp"; }

emit "// Code generated by scripts/update-tool-checksums.sh; DO NOT EDIT."
emit "// Run \`scripts/update-tool-checksums.sh\` after bumping a pinned version."
emit ""
emit "package tools"
emit ""
emit "// pinnedVersion is the version devrig fetches and validates per tool."
emit "var pinnedVersion = map[Tool]string{"
emit "	Kubectl: \"${KUBECTL_VERSION}\","
emit "	Helm:    \"${HELM_VERSION}\","
emit "	K3d:     \"${K3D_VERSION}\","
emit "}"
emit ""
emit "// checksums maps \"<tool>/<version>/<goos>/<goarch>\" to the expected"
emit "// SHA-256 of the downloaded artifact (the raw binary for kubectl/k3d, the"
emit "// .tar.gz for helm)."
emit "var checksums = map[string]string{"

# Pre-fetch the k3d combined checksum file once.
k3d_sums="$(curl -fsSL "https://github.com/k3d-io/k3d/releases/download/v${K3D_VERSION}/checksums.txt")"

for p in "${PLATFORMS[@]}"; do
  os="${p%/*}"; arch="${p#*/}"
  exe=""; [ "$os" = "windows" ] && exe=".exe"

  # kubectl: bare .sha256 file containing just the hash.
  kc="$(curl -fsSL "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/${os}/${arch}/kubectl${exe}.sha256")"
  emit "	\"kubectl/${KUBECTL_VERSION}/${os}/${arch}\": \"${kc}\","

  # helm: "<hash>  <filename>" .sha256sum for the tar.gz.
  hm="$(curl -fsSL "https://get.helm.sh/helm-v${HELM_VERSION}-${os}-${arch}.tar.gz.sha256sum" | awk '{print $1}')"
  emit "	\"helm/${HELM_VERSION}/${os}/${arch}\": \"${hm}\","

  # k3d: parse the combined checksums.txt for this asset. Filenames there are
  # path-prefixed (e.g. "_dist/k3d-linux-amd64"), so match on the basename.
  asset="k3d-${os}-${arch}${exe}"
  kd="$(printf '%s\n' "$k3d_sums" | awk -v a="$asset" '{ n=$2; sub(/.*\//,"",n); if (n==a) {print $1; exit} }')"
  [ -z "$kd" ] && { echo "ERROR: no k3d checksum for $asset" >&2; exit 1; }
  emit "	\"k3d/${K3D_VERSION}/${os}/${arch}\": \"${kd}\","
done

emit "}"

gofmt -w "$tmp"
mv "$tmp" "$out"
echo "Wrote $out"
